### ISSUE TITLE
0.1.4 todo

### ISSUE THREAD

**Issue by jmoiron** [jmoiron/Gregtech-Extended-Chemistry#4]
- [x] use gtceu `formic acid` and remove gtec version
- [x] full-dust `platinum residue dust` ebf alternative (instead of 2 small potassium disulfate dusts)
- [x] liquid potassium needs some kind of use (solidifer?)
